export const DOCKER_DEFAULTS = {
  // Local repo configurations (running outside Docker)
  local: {
    postgres: {
      host: "localhost",
      port: "5432",
      username: "default_user",
      password: "default_password",
      database: "default_db",
      name: "default_db",
      protocol: "postgresql",
      connectionUrl:
        "postgresql://default_user:default_password@localhost:5432/default_db",
      source: "docker" as const,
      isInternal: true,
    },
    timescaledb: {
      host: "localhost",
      port: "5432",
      username: "default_user",
      password: "default_password",
      database: "default_timescale_db",
      name: "default_timescale_db",
      protocol: "postgresql",
      connectionUrl:
        "postgresql://default_user:default_password@localhost:5432/default_timescale_db",
      source: "docker" as const,
      isInternal: true,
    },
    redis: {
      host: "localhost",
      port: "6379",
      username: undefined,
      password: undefined,
      database: undefined,
      protocol: "redis",
      connectionUrl: "redis://localhost:6379",
      source: "docker" as const,
      isInternal: true,
    },
    rabbitmq: {
      host: "localhost",
      port: "5672",
      username: "guest",
      password: "guest",
      protocol: "amqp",
      connectionUrl: "amqp://guest:guest@localhost:5672",
      source: "docker" as const,
      isInternal: true,
    },
  },
  // Dockerized repo configurations (running inside Docker containers)
  dockerized: {
    postgres: {
      host: "postgres",
      port: "5432",
      username: "default_user",
      password: "default_password",
      name: "default_db",
      database: "default_db",
      protocol: "postgresql",
      connectionUrl:
        "postgresql://default_user:default_password@postgres:5432/default_db",
      source: "docker" as const,
      isInternal: true,
    },
    timescaledb: {
      host: "timescaledb",
      port: "5432",
      username: "default_user",
      name: "default_timescale_db",
      password: "default_password",
      database: "default_timescale_db",
      protocol: "postgresql",
      connectionUrl:
        "postgresql://default_user:default_password@timescaledb:5432/default_timescale_db",
      source: "docker" as const,
      isInternal: true,
    },
    redis: {
      host: "redis",
      port: "6379",
      username: undefined,
      password: undefined,
      database: undefined,
      protocol: "redis",
      connectionUrl: "redis://redis:6379",
      source: "docker" as const,
      isInternal: true,
    },
    rabbitmq: {
      host: "rabbitmq",
      port: "5672",
      username: "guest",
      password: "guest",
      protocol: "amqp",
      connectionUrl: "amqp://guest:guest@rabbitmq:5672",
      source: "docker" as const,
      isInternal: true,
    },
  },
} as const;
